

2024-08-17 18:40:07.636257
18:40:072024-08-17 18:40:07,695 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 18:40:07,698 - __main__ - INFO - [client.py:141] - Client: Connected
2024-08-17 18:40:07,739 - __main__ - INFO - [client.py:158] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 18:40:08,910 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176523)
2024-08-17 18:40:09,234 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 24
2024-08-17 18:40:37,100 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176527)
2024-08-17 18:40:37,513 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 28
2024-08-17 18:41:05,303 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176531)
2024-08-17 18:41:05,794 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 32
2024-08-17 18:41:33,578 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176535)
2024-08-17 18:41:34,063 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 36
2024-08-17 18:42:01,783 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176539)
2024-08-17 18:42:01,810 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 40
2024-08-17 18:42:28,034 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176543)
2024-08-17 18:42:28,064 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 44
2024-08-17 18:42:54,228 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176547)
2024-08-17 18:42:54,313 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 48
2024-08-17 18:43:20,405 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176551)
2024-08-17 18:43:20,543 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 52
2024-08-17 18:43:46,641 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176555)
2024-08-17 18:43:46,785 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 56
2024-08-17 18:44:12,865 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176559)
2024-08-17 18:44:13,018 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 60
2024-08-17 18:44:39,058 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176563)
2024-08-17 18:44:39,231 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 64
2024-08-17 18:45:05,316 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176567)
2024-08-17 18:45:05,449 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 68
2024-08-17 18:45:31,540 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176571)
2024-08-17 18:45:31,679 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 72
2024-08-17 18:45:57,783 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176575)
2024-08-17 18:45:57,923 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 76
2024-08-17 18:46:23,952 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176579)
2024-08-17 18:46:24,158 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 80
2024-08-17 18:46:51,506 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176583)
2024-08-17 18:46:51,918 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 84
2024-08-17 18:47:19,665 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176587)
2024-08-17 18:47:20,109 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 88
2024-08-17 18:47:47,301 - __main__ - WARNING - [client.py:145] - connection closed with server
2024-08-17 18:47:47,301 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 18:47:57,322 - __main__ - INFO - [client.py:141] - Client: Connected
2024-08-17 18:47:57,373 - __main__ - INFO - [client.py:158] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 18:47:58,144 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176596)
2024-08-17 18:47:58,311 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 97
2024-08-17 18:48:24,428 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176515)
2024-08-17 18:48:24,546 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 16
2024-08-17 18:48:50,622 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 886358176589)
2024-08-17 18:48:50,783 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 90
2024-08-17 18:52:22,647 - __main__ - WARNING - [client.py:145] - connection closed with server
2024-08-17 18:52:22,657 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 18:52:32,675 - __main__ - INFO - [client.py:141] - Client: Connected
2024-08-17 18:52:32,690 - __main__ - INFO - [client.py:158] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 18:52:33,810 - __main__ - INFO - [client.py:158] - received message from: server -> (Task: 83004666994)
2024-08-17 18:52:34,169 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 5


2024-08-17 19:36:28.444362
19:36:282024-08-17 19:36:28,502 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 19:36:28,504 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:36:28,551 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:36:48,226 - __main__ - INFO - [client.py:161] - received message from: server -> (Task: 48719275253)
2024-08-17 19:36:48,406 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 4
2024-08-17 19:38:26,172 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 19:38:26,172 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 19:38:36,191 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:38:36,238 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 19:38:55,865 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 19:38:55,873 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 19:39:05,896 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:39:05,912 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))


2024-08-17 19:39:31.894468
19:39:312024-08-17 19:39:31,943 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 19:39:31,945 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:39:31,991 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:40:11,901 - __main__ - INFO - [client.py:161] - received message from: server -> (Task: 94919487433)
2024-08-17 19:40:12,094 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 4
2024-08-17 19:47:07,495 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 19:47:07,495 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 19:47:17,522 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:47:17,568 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:48:49,677 - __main__ - INFO - [client.py:161] - received message from: server -> (restart_envy())


2024-08-17 19:48:51.204421
19:48:512024-08-17 19:48:51,258 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 19:48:51,260 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:48:51,309 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:48:54,280 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 19:48:54,280 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 19:49:04,298 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:49:04,340 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:49:38,713 - __main__ - INFO - [client.py:161] - received message from: server -> (Task: 56152314653)
2024-08-17 19:49:38,946 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 4
2024-08-17 19:56:41,283 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 19:56:41,283 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 19:56:51,305 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 19:56:51,320 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 19:57:06,011 - __main__ - INFO - [client.py:161] - received message from: server -> (Task: 84609263773)
2024-08-17 19:57:06,498 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 4
2024-08-17 20:04:55,503 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 20:04:55,503 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 20:05:05,525 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:05:05,538 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'LAB2-12', ))
2024-08-17 20:05:06,063 - __main__ - INFO - [client.py:161] - received message from: server -> (Task: 14336104413)
2024-08-17 20:05:06,528 - __main__ - INFO - [envy_plugin.py:17] - Plugin-Debug: Initialized -> Frame: 4
2024-08-17 20:13:30,546 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 20:13:30,547 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 20:13:40,565 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:13:40,577 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:30:31,118 - __main__ - INFO - [client.py:161] - received message from: server -> (restart_envy())


2024-08-17 20:30:32.186113
20:30:322024-08-17 20:30:32,239 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 20:30:32,242 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:30:32,256 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:30:35,266 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 20:30:35,266 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 20:30:45,291 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:30:45,337 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:30:49,421 - __main__ - INFO - [client.py:161] - received message from: server -> (restart_envy())


2024-08-17 20:30:50.893768
20:30:502024-08-17 20:30:50,939 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 20:30:50,941 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:30:50,953 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:30:52,449 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 20:30:52,449 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 20:31:02,470 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:31:02,510 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:46:43,548 - __main__ - INFO - [client.py:161] - received message from: server -> (restart_envy())


2024-08-17 20:46:45.084908
20:46:452024-08-17 20:46:45,137 - __main__ - INFO - [envy.py:127] - Started Envy
2024-08-17 20:46:45,140 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:46:45,187 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-03', ))
2024-08-17 20:46:48,177 - __main__ - WARNING - [client.py:148] - connection closed with server
2024-08-17 20:46:48,177 - __main__ - INFO - [envy.py:213] - electing new server
2024-08-17 20:46:58,199 - __main__ - INFO - [client.py:144] - Client: Connected
2024-08-17 20:46:58,245 - __main__ - INFO - [client.py:161] - received message from: server -> (fill_buffer(self, 'server_name', 'lab2-04', ))
